#spring.datasource.url=jdbc:postgresql://localhost:5432/servers-app
#spring.datasource.username=postgres
#spring.datasource.password=root
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/servers-app
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    show-sql: true